name: flocalizer
description: An extensible and powerful flutter localization package
version: 0.0.3
homepage: "https://github.com/jayvhaile/flocalizer.git"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
